global:
  scrape_interval: 5s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
- job_name: 'nginx exporter'
  metrics_path: /metrics
  static_configs:
    - targets:
        - prometheus-exporter:9113